name: Build

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**.md"
    tags:
      - "v*"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: "Build"
        run: swift build -c release
      - name: "Prepare artifact"
        working-directory: .build/release
        run: 7z a -tzip open-terminal-at-folder.zip open-terminal-at-folder
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: open-terminal-at-folder
          path: .build/release/open-terminal-at-folder.zip
          if-no-files-found: error
  make-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [build]
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          path: .build/release
      - name: "Release"
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            .build/release/open-terminal-at-folder.zip
